### ISSUE TITLE
Bump version of npm to 2?

### ISSUE THREAD

**Issue by lebolo** [iclanzan/grunt-npm-install#5]
Hello,

I was able to checkout the latest code and bump the version of npm to 2.5.1 (had to bump grunt-contrib-nodeunit to 0.4.1). `grunt test` gives ok.

Would it be possible to bump npm to v2.x to allow npm to install local modules (new feature in 2.x)?

**Comment by iclanzan** [comment]
Sure, do you want to submit a pul request?
